- .github/workflows/check.yml
- CHANGELOG.md
- Dockerfile
- Dockerfile.tests
- rust-toolchain.toml
The PR introduces `rust-toolchain.toml` file to have a single source of truth on the Rust toolchain for the project. Having `rust-toolchain.toml` simplifies development environment setup and mitigates build instructions because they should not specify toolchain parameters explicitly anymore.
> Introduce rust-toolchain.toml

- CHANGELOG.md
- pallets/ddc-staking/src/benchmarking.rs
- pallets/ddc-staking/src/lib.rs
- pallets/ddc-staking/src/testing_utils.rs
- pallets/ddc-staking/src/weights.rs
- runtime/cere-dev/src/lib.rs
Updates
- `pallet-ddc-staking` now requires one fixed size bond for both `Storage` and `Edge` roles instead of the bond limited by the lower boundary only
- New `set_staking_configs` call in `pallet-ddc-staking` to allow to set DDC Staking bond size by the authority
- `spec_version` for the `cere-dev` runtime incremented
> Fixed bond size for DDC Staking

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- cli/Cargo.toml
- cli/src/command.rs
- node/client/Cargo.toml
- node/service/Cargo.toml
- rpc/Cargo.toml
- runtime/cere-dev/Cargo.toml
- runtime/cere-dev/constants/Cargo.toml
- runtime/cere/Cargo.toml
- runtime/cere/constants/Cargo.toml
- runtime/common/Cargo.toml
As in [Telemetry](https://telemetry.polkadot.io/#list/0x81443836a9a24caaa23f1241897d1235717535711d1d3fe24eae4fdc942c092c) we already can see v3.0.0 we've decided to start new node from v4.0.0 to avoid confusion in future.
> Set version to 4.0.0

- CHANGELOG.md
- Cargo.lock
- pallets/ddc-staking/Cargo.toml
- pallets/ddc-staking/src/benchmarking.rs
- pallets/ddc-staking/src/lib.rs
- pallets/ddc-staking/src/testing_utils.rs
- runtime/cere-dev/Cargo.toml
- runtime/cere-dev/src/lib.rs
- runtime/cere/src/lib.rs
* Remove `StoragePrefs` and `EdgePrefs` from blockchain storage items and extrinsics parameters,
* Store CDN and storage network participants list in the vector, instead of the map,
* Synchronize era counter with DAC,
* Distinct bond size requirements for `Storage` and `Edge` roles.
> A set of updates for pallet-ddc-staking

- CHANGELOG.md
- pallets/ddc-staking/src/benchmarking.rs
- pallets/ddc-staking/src/lib.rs
- pallets/ddc-staking/src/testing_utils.rs
- runtime/cere-dev/src/lib.rs
- runtime/cere/src/lib.rs
Allow users to specify the cluster ID that they are willing to join and store it together with the staker account.
> Introduce clusters in DDC Staking

- CHANGELOG.md
- pallets/ddc-staking/src/lib.rs
- runtime/cere-dev/src/lib.rs
- runtime/cere/src/lib.rs
- DDC staking requirements now distinct for each DDC cluster
- DDC participant stake chilling is delayed if the delay is not explicitly set to zero
Migrations are missed because only the dev runtime is updated.
> Distinct staking settings for each cluster and deferred "chill"

- runtime/cere-dev/src/lib.rs
- runtime/cere/src/lib.rs
[This missed migration](https://github.com/paritytech/substrate/pull/12083/files) caused smart contracts disappearance. We missed it as we rely on the migration of Polkadot source code but Polkadot doesn't have smart contracts in its dependencies. In the future, we need to check Substrate source code too.
> Fix contracts dissapearing

- .github/workflows/check.yaml
- .vscode/settings.json
- scripts/pre-commit.sh
We no longer need to pass toolchain to cargo fmt invocations because it is specified in `rust-toolchain.toml`. At the same time, preserving the toolchain argument may become an issue if the latest `nightly` defaults are changed and become not the same as defaults for the toolchain specified in `rust-toolchain.toml`.
> Use default toolchain for cargo fmt

- cli/src/command.rs
Chain specifications with IDs prefixed by `cere_dev` are [considered](https://github.com/search?q=repo%3ACerebellum-Network%2Fblockchain-node%20is_cere_dev&type=code) to use `cere-dev` runtime which we can currently force by `--force-cere-dev`. But in a `build-spec` subcommand the key is not implemented. Polkadot [checks](https://github.com/paritytech/polkadot-sdk/blob/50de035f6d33b7233fd263892dd263d52b997f5c/polkadot/cli/src/command.rs#L148) for a prefix in the specification loader which we may want to implement as well. It will fix the `build-spec` behavior for chains that require `cere-dev` runtime for specifications loaded from a file.
> Fix runtime loading from file for cere-dev chains

- CHANGELOG.md
- README.md
- zombienet/0000-block-building/block-building.toml
- zombienet/0000-block-building/block-building.zndsl
- zombienet/0000-block-building/transaction-gets-finalized.js
- zombienet/0001-ddc-validation/ddc-validation.toml
This adds a couple [zombienet](https://github.com/paritytech/zombienet) configurations to test block building and spawn a network for DDC validation debugging.
> Zombienet integration

- Cargo.lock
- pallets/ddc-clusters/Cargo.toml
- pallets/ddc-clusters/src/cluster.rs
- pallets/ddc-clusters/src/lib.rs
Allow setting a DDC cluster extension contract address during the creation of a cluster. And test a new node for authorization by the extension contract before adding it to the cluster. Not tested.
> Cluster node authorization by extension contract

- pallets/ddc-clusters/src/lib.rs
- pallets/ddc-staking/src/lib.rs
- runtime/cere-dev/src/lib.rs
New `fast_chill` extrinsic call hander which allows cluster node candidates to revoke their DDC Staking stake quickly in case they are not attending in any cluster.
Also an additional check in the `add_node` to ensure the candidate is not planning to chill when we consider adding it to the cluster.
Manually tested locally.
> Allow chill in the next era for nodes not attending any cluster

- pallets/ddc-clusters/src/lib.rs
- primitives/src/lib.rs
- runtime/cere-dev/src/lib.rs
* Cluster authorization extension contract message definition updated to `is_authorized(node_provider: AccountId, node: Vec<u8>, node_variant: u8) -> bool`. Future implementations may define `ddc_primitives::NodePubKey` for the `ink!` side to use it instead of the byte array.
* Custom `NodePubKey::variant_as_number()` function created instead of the `From` implementation in order to not confuse the user with the conversion provided by the specific type of the key variant.
Manually tested locally.
> Pass provider and node ids to the auth extension

- pallets/ddc-clusters/src/lib.rs
- pallets/ddc-staking/src/lib.rs
- pallets/ddc-staking/src/mock.rs
- traits/src/cluster.rs
- Replace cluster settings retrieval from ddc-staking to ddc-clusters
> substitute bond size check with cluster gov params

- pallets/ddc-customers/src/lib.rs
Based on a discussion with @Raid5594 and @khssnv we concluded that it is better to use a cryptographically safe hasher here as in theory a malicious user can generate a number of accounts with the same prefix by brute-forcing and this way create an unbalanced tree.
No migration is needed at the moment as neither Devnet nor Testnet has any active Ledgers.
> 'StorageHasher' type for the Ledger map is changed to a more secure one

- Cargo.lock
- Cargo.toml
- cli/Cargo.toml
- node/client/Cargo.toml
- node/service/Cargo.toml
- pallets/chainbridge/Cargo.toml
- pallets/ddc-clusters/Cargo.toml
- pallets/ddc-customers/Cargo.toml
- pallets/ddc-metrics-offchain-worker/Cargo.toml
- pallets/ddc-nodes/Cargo.toml
- pallets/ddc-staking/Cargo.toml
- pallets/ddc/Cargo.toml
- pallets/ddc/README.md
- pallets/erc20/Cargo.toml
- pallets/erc721/Cargo.toml
- primitives/Cargo.toml
- rpc/Cargo.toml
- runtime/cere-dev/Cargo.toml
- runtime/cere-dev/constants/Cargo.toml
- runtime/cere/Cargo.toml
- runtime/cere/constants/Cargo.toml
- runtime/common/Cargo.toml
- traits/Cargo.toml
Since we're using substrate dependencies based on a specific versioned branch, usage of `version` in the cargo dependency is redundant.
Cleaned it all substrate deps `version` tag.
> Remove redundant versions

- cli/src/cli.rs
After the [recent substrate update](https://github.com/Cerebellum-Network/blockchain-node/commit/728ad51cbf2636a31ac10e976153e9d2fcdacda4) to `polkadot-v0.9.31` which contains `clap` major version upgrade from `3` to `4` the node panics at the startup.
There are similar changes as we have here in the diff for `substrate-node`: https://github.com/paritytech/substrate/compare/polkadot-v0.9.30..polkadot-v0.9.31#diff-11f6080619429c3df8cc5afa5767fba0c3ae8ab867a163e782ae7e30df1082e3R23
> Fix node startup panic after clap upgrade to v4

- Cargo.lock
- node/service/src/chain_spec.rs
- pallets/ddc-clusters/Cargo.toml
- pallets/ddc-clusters/src/cluster.rs
- pallets/ddc-clusters/src/lib.rs
- primitives/src/lib.rs
* `GenesisConfig` implementation for `pallet-ddc-clusters`.
* It skips `add_node` with checks and directly writes to the storage because currently cluster authorization smart contract is mandatory, but can't be set in in a genesis state (`pallet-contracts` does not implement `GenesisConfig`). Future implementation may make the extension contract optional and use `add_node` to check if the user set `ddc-staking` and `ddc-nodes` genesis consistently.
> Genesis config for `pallet-ddc-clusters`

- pallets/ddc-staking/src/benchmarking.rs
- pallets/ddc-staking/src/mock.rs
- pallets/ddc-staking/src/tests.rs
> improve coverage for ddc-staking

- node/service/chain-specs/example.json
Related to https://github.com/Cerebellum-Network/blockchain-node/pull/200.
Tested manually with a local node.
> Add storage node mode to `example.json` chain spec

- node/service/chain-specs/example.json
- pallets/ddc-clusters/src/testing_utils.rs
- pallets/ddc-clusters/src/tests.rs
- pallets/ddc-nodes/src/benchmarking.rs
- pallets/ddc-nodes/src/lib.rs
- pallets/ddc-nodes/src/node.rs
- pallets/ddc-nodes/src/storage_node.rs
- pallets/ddc-nodes/src/testing_utils.rs
- pallets/ddc-nodes/src/tests.rs
- pallets/ddc-staking/src/benchmarking.rs
- pallets/ddc-staking/src/testing_utils.rs
- primitives/src/lib.rs
This PR introduces `domain` and `ssl` fields for storage node params
> DDC Storage node params updated with `domain` and `ssl` fields; Tests are enhanced

- Cargo.lock
- pallets/chainbridge/Cargo.toml
- pallets/chainbridge/src/lib.rs
- pallets/chainbridge/src/mock.rs
- pallets/chainbridge/src/tests.rs
- pallets/erc20/src/lib.rs
- pallets/erc20/src/mock.rs
- pallets/erc721/src/lib.rs
- pallets/erc721/src/tests.rs
- erc20 pallet syntax update
- erc721 pallet syntax update
- chainbridge pallet syntax update
> add new syntax for erc20, erc721 and chainbridge pallet

- node/service/src/chain_spec.rs
Fix the issue @yahortsaryk reported in [Slack](https://cere-network.slack.com/archives/C04S79C3A11/p1703786484555029).
The issue was caused by misconfiguration of `dev` chain spec
> Configure chain properties for dev runtime

- .github/workflows/stage.yaml
This PR fixes the docker build push by tagging the staging image with the full github commit SHA.
> Build an image with the full github SHA

- pallets/chainbridge/src/lib.rs
- pallets/chainbridge/src/mock.rs
- pallets/erc20/src/lib.rs
- runtime/cere-dev/src/lib.rs
- runtime/cere/src/lib.rs
Constant declarations were accidentally removed in #210
> Chainbridge constants fix

- pallets/chainbridge/src/lib.rs
- pallets/chainbridge/src/mock.rs
- pallets/erc20/src/mock.rs
- runtime/cere-dev/src/lib.rs
- runtime/cere/src/lib.rs
> Rename constant to what bridge relayers expect

- runtime/cere/src/lib.rs
It cost  a lot of Cere tokens to create a pre-image.
> Lower preimage deposit

- CHANGELOG.md
- runtime/cere-dev/src/lib.rs
- runtime/cere/src/lib.rs
> Set daily burn rate for Cere tokens

- runtime/cere/src/lib.rs
This hotfix will be used for a runtime upgrade to 0.9.42 without the burn enabled.
> Hotfix: Disable burn on 0.9.42

- runtime/cere/src/lib.rs
Contracts pallet executes migrations in sequence depending on weight available. If not, it schedules a multi-block migration sequence. It's better to have it execute last.
> Reorder migrations

- runtime/cere/src/lib.rs
Reverts Cerebellum-Network/blockchain-node#280
> Revert "Hotfix: enable burn and migrations"

- runtime/cere-dev/src/lib.rs
- runtime/cere/src/lib.rs
> Fix of the substrate 1.1.0 and OpenGov to pass the try-runtime check

- CHANGELOG.md
- pallets/ddc-customers/src/lib.rs
- pallets/ddc-customers/src/tests.rs
- runtime/cere-dev/src/lib.rs
- runtime/cere/src/lib.rs
Companion for [Hotfix #333](https://github.com/Cerebellum-Network/blockchain-node/pull/333)
> fix: depositing extra amount is fixed (#333)

- runtime/cere-dev/src/lib.rs
The patch allows smaller clusters in test environments which should not necessary provide minimal redundancy guarantees.
> Remove `cere-dev` min cluster redundancy requirements

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- node/service/src/chain_spec.rs
- runtime/cere-dev/src/governance/mod.rs
- runtime/cere-dev/src/lib.rs
- runtime/cere/src/governance/mod.rs
- runtime/cere/src/lib.rs
Forwarding #351 to the Testnet
> Release 5.3.1

- pallets/ddc-verification/src/lib.rs
- runtime/cere-dev/src/lib.rs
- runtime/cere/src/lib.rs
> OCW additional logs

- .github/workflows/ci.yaml
- runtime/cere-dev/src/lib.rs
The path updates `ci.yaml` workflow runners to Ubuntu 24.04 already used for the other workflows. It brings a more recent `protoc` package need for https://github.com/Cerebellum-Network/blockchain-node/pull/458.
> Update `ci.yaml` runners to Ubuntu 24.04

- .github/workflows/ci.yaml
- node/service/src/chain_spec.rs
- pallets/ddc-payouts/src/mock.rs
- pallets/ddc-verification/src/lib.rs
- pallets/ddc-verification/src/mock.rs
- pallets/ddc-verification/src/tests.rs
- primitives/src/lib.rs
- primitives/src/traits/validator.rs
- runtime/cere-dev/src/lib.rs
- runtime/cere/src/lib.rs
This PR removes the excessive `set_current_validator` extrinsic and applies the generic approach for collecting the verification key from the keystore as it is done in the [substrate source code](https://github.com/paritytech/polkadot-sdk/blob/polkadot-v1.2.0/substrate/frame/system/src/offchain.rs#L178)
> Collecting validator verification key in Substrate - generic way

- primitives/src/lib.rs
The current version fails at `cargo check` for a single crate with the following error.
<details>
<summary>$ cargo check -p pallet-ddc-verification</summary>
```console
$ cargo check -p pallet-ddc-verification
Checking ddc-primitives v6.1.0 (/home/khassanov/Workspace/github.com/Cerebellum-Network/blockchain-node/primitives)
error[E0412]: cannot find type `String` in this scope
--> primitives/src/lib.rs:327:3
|
327 |         app_crypto!(sr25519, DAC_VERIFICATION_KEY_TYPE);
|         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope
|
= note: this error originates in the macro `$crate::app_crypto_pair_functions_if_std` which comes from the expansion of the macro `app_crypto` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider importing one of …
```
> Fix `ddc-primitives` missing import check error

- pallets/ddc-verification/src/lib.rs
- runtime/cere-dev/src/lib.rs
- runtime/cere/src/lib.rs
This introduces a mutex for `pallet-ddc-verification` OCW to allow only once instance of it to run at a time. It also reduces verification attempts period to a minimum to try to do the verification or progress an era payout each block.
> Allow only one instance of DDC verification OCW to run at a time

- runtime/cere-dev/src/lib.rs
- runtime/cere/src/lib.rs
With https://github.com/Cerebellum-Network/blockchain-node/pull/479 we allow only one instance of a DDC verification OCW to run at a time we can safely make an attempt each block to speedup validation and payouts on networks with `cere` runtime.
> Run DDC verification OCW each block on `cere` runtime

- runtime/cere-dev/src/lib.rs
- runtime/cere/src/lib.rs
Migration `pallet-ddc-payout` v2 for `cere-dev`.
> Migration `pallet-ddc-payout` v2 for `cere-dev`

- Cargo.lock
- Cargo.toml
- pallets/pool-withdrawal-fix/Cargo.toml
- pallets/pool-withdrawal-fix/src/lib.rs
- runtime/cere-dev/Cargo.toml
- runtime/cere-dev/src/lib.rs
- runtime/cere/Cargo.toml
- runtime/cere/src/lib.rs
> Added pool-withdrawal-fix
