Cerebellum-Network/blockchain-node

CHANGELOG.md
README.md
cli/src/command.rs
node/service/src/chain_spec.rs

Added ability to run local testnet with Cere Dev runtime. Required steps can be found in Readme.

Added Cere Dev Local Testnet config

---

CHANGELOG.md
Cargo.lock
Cargo.toml
cli/Cargo.toml
node/client/Cargo.toml
node/service/Cargo.toml
rpc/Cargo.toml
runtime/cere-dev/Cargo.toml
runtime/cere-dev/constants/Cargo.toml
runtime/cere/Cargo.toml
runtime/cere/constants/Cargo.toml
runtime/common/Cargo.toml

Changes can be found [here](https://github.com/Cerebellum-Network/blockchain-node/blob/release/4.1.0/CHANGELOG.md#410).

Release 4.1.0 (to dev)

---

CHANGELOG.md
Cargo.lock
Cargo.toml
cli/Cargo.toml
node/client/Cargo.toml
node/service/Cargo.toml
pallets/chainbridge/Cargo.toml
pallets/ddc-metrics-offchain-worker/Cargo.toml
pallets/ddc/Cargo.toml
pallets/erc20/Cargo.toml
pallets/erc721/Cargo.toml
rpc/Cargo.toml
runtime/cere-dev/Cargo.toml
runtime/cere-dev/constants/Cargo.toml
runtime/cere-dev/src/lib.rs
runtime/cere/Cargo.toml
runtime/cere/constants/Cargo.toml
runtime/cere/src/lib.rs
runtime/common/Cargo.toml

[Release notes.](https://github.com/Cerebellum-Network/blockchain-node/blob/release/4.3.0/CHANGELOG.md#430)

Release 4.3.0

---

.github/workflows/check.yml
.vscode/settings.json
cli/src/command.rs
node/service/src/lib.rs
pallets/chainbridge/src/lib.rs
pallets/chainbridge/src/mock.rs
pallets/chainbridge/src/tests.rs
pallets/ddc-metrics-offchain-worker/src/lib.rs
pallets/ddc-metrics-offchain-worker/src/tests/mod.rs
pallets/ddc-metrics-offchain-worker/src/tests/test_runtime.rs
pallets/ddc/src/lib.rs
pallets/ddc/src/mock.rs
pallets/erc20/src/lib.rs
pallets/erc721/src/lib.rs
pallets/erc721/src/mock.rs
pallets/erc721/src/tests.rs
rpc/src/lib.rs
runtime/cere-dev/src/impls.rs
runtime/cere-dev/src/lib.rs
runtime/cere/src/impls.rs
runtime/cere/src/lib.rs
runtime/common/src/lib.rs
scripts/init.sh
scripts/pre-commit.sh

* Rustfmt on save for VS Code
* Rustfmt on pre-commit
* Rustfmt on push in CI before build
Also, the existing code base was updated by `cargo +nightly fmt`.

Force rustfmt

---

CHANGELOG.md
Cargo.lock
README.md
cli/Cargo.toml
cli/src/cli.rs
cli/src/command.rs
node/service/src/lib.rs
pallets/ddc-validator/src/lib.rs
zombienet/0001-ddc-validation/ddc-validation.toml

Please check `CHANGELOG.md` patch for details.

DAC DataModel HTTP endpoint from CLI

---

.github/workflows/check.yaml

The patch also updates `check.yaml` workflow dependencies versions and adds a caching step.

Enable `check.yaml` workflow on push on all branches

---

.cargo/config.toml
.github/workflows/check.yaml
Cargo.toml
cli/Cargo.toml
dprint.json
node/client/Cargo.toml
node/service/Cargo.toml
pallets/chainbridge/Cargo.toml
pallets/ddc-clusters/Cargo.toml
pallets/ddc-customers/Cargo.toml
pallets/ddc-metrics-offchain-worker/Cargo.toml
pallets/ddc/Cargo.toml
pallets/erc20/Cargo.toml
pallets/erc721/Cargo.toml
primitives/Cargo.toml
rpc/Cargo.toml
runtime/cere-dev/Cargo.toml
runtime/cere-dev/constants/Cargo.toml
runtime/cere/Cargo.toml
runtime/cere/constants/Cargo.toml
runtime/common/Cargo.toml
rust-toolchain.toml
rustfmt.toml
traits/Cargo.toml
zombienet/0000-block-building/block-building.toml
zombienet/0001-ddc-validation/ddc-validation.toml

[dprint](https://github.com/dprint/dprint) is a tool to check formatting of Cargo.toml files which makes sure consistent ordering of dependencies and their format.

Add dprint CI check

---

.github/auto_assign.yml

- Assigns creator or the PR
- Selects 2 random reviewers from a predefined list.

Add auto-assign to github PRs

---

pallets/ddc-customers/src/mock.rs

add missing mocks

---

pallets/ddc-clusters/src/tests.rs
pallets/ddc-nodes/src/cdn_node.rs
pallets/ddc-nodes/src/lib.rs
pallets/ddc-nodes/src/node.rs
pallets/ddc-nodes/src/storage_node.rs
pallets/ddc-nodes/src/testing_utils.rs
pallets/ddc-nodes/src/tests.rs
pallets/ddc-staking/src/benchmarking.rs
pallets/ddc-staking/src/lib.rs
pallets/ddc-staking/src/mock.rs
pallets/ddc-staking/src/testing_utils.rs
pallets/ddc-staking/src/weights.rs
primitives/src/lib.rs
runtime/cere-dev/src/lib.rs
traits/src/node.rs

- update benchmarking
- update weights

provide benchmarking and weights for ddc-staking after changes

---

pallets/ddc-payouts/src/lib.rs
pallets/ddc-payouts/src/tests.rs

Payout type fix 0.9.30

---

CHANGELOG.md
Cargo.lock
Cargo.toml
cli/Cargo.toml
node/client/Cargo.toml
node/service/Cargo.toml
pallets/chainbridge/Cargo.toml
pallets/ddc-metrics-offchain-worker/Cargo.toml
pallets/ddc-staking/Cargo.toml
pallets/ddc/Cargo.toml
pallets/erc20/Cargo.toml
pallets/erc721/Cargo.toml
rpc/Cargo.toml
runtime/cere-dev/Cargo.toml
runtime/cere-dev/constants/Cargo.toml
runtime/cere-dev/src/lib.rs
runtime/cere/Cargo.toml
runtime/cere/constants/Cargo.toml
runtime/cere/src/lib.rs
runtime/common/Cargo.toml

Update governance-related constants

Create release 4.8.2 release

---

Cargo.lock
Cargo.toml
cli/Cargo.toml
node/client/Cargo.toml
node/service/Cargo.toml
pallets/chainbridge/Cargo.toml
pallets/ddc-clusters/Cargo.toml
pallets/ddc-metrics-offchain-worker/Cargo.toml
pallets/ddc-nodes/Cargo.toml
pallets/ddc-payouts/Cargo.toml
pallets/ddc-staking/Cargo.toml
pallets/ddc/Cargo.toml
pallets/erc20/Cargo.toml
pallets/erc721/Cargo.toml
rpc/Cargo.toml
runtime/cere-dev/Cargo.toml
runtime/cere-dev/constants/Cargo.toml
runtime/cere-dev/src/lib.rs
runtime/cere/Cargo.toml
runtime/cere/constants/Cargo.toml
runtime/cere/src/lib.rs
runtime/common/Cargo.toml

Sets the proper versions and align the runtime versions

Release-4.8.2

---

.github/workflows/publish-docker-image-to-dockerhub.yaml

Add latest tag to docker image

---

runtime/cere-dev/src/lib.rs

Adds contract migration to take the contracts pallet into version 9

Add contract migration to dev

---

pallets/chainbridge/src/lib.rs
pallets/chainbridge/src/mock.rs
pallets/erc20/src/mock.rs
runtime/cere-dev/src/lib.rs
runtime/cere/src/lib.rs

Rename constant to what bridge relayers expect

---

CHANGELOG.md
Cargo.lock
pallets/ddc-payouts/Cargo.toml
pallets/ddc-payouts/src/benchmarking.rs
pallets/ddc-payouts/src/lib.rs
pallets/ddc-payouts/src/tests.rs

payout start/end

---

CHANGELOG.md
pallets/ddc-customers/src/lib.rs
pallets/ddc-customers/src/tests.rs
pallets/ddc-payouts/src/lib.rs
pallets/ddc-payouts/src/mock.rs
pallets/ddc-payouts/src/tests.rs

- [ X] Change has been tested locally.
- [ X] Change adds / updates tests.
- [ X] Changelog doc updated.

events + cummulative charge fix

---

.github/workflows/ecr.yaml

Prevent building an image for each PR... just build the image for dev, master branches & hotfix, release PRs.

Run ECR on push to dev & master

---

Cargo.toml
node/cli/Cargo.toml
node/client/Cargo.toml
node/rpc/Cargo.toml
node/service/Cargo.toml
pallets/chainbridge/Cargo.toml
pallets/ddc-clusters/Cargo.toml
pallets/ddc-customers/Cargo.toml
pallets/ddc-nodes/Cargo.toml
pallets/ddc-payouts/Cargo.toml
pallets/ddc-staking/Cargo.toml
pallets/erc20/Cargo.toml
pallets/erc721/Cargo.toml
primitives/Cargo.toml
runtime/cere-dev/Cargo.toml
runtime/cere/Cargo.toml
runtime/common/Cargo.toml

Improves dependency management by having workspace dependencies which inner crates inherit from.
DEPENDS ON: #253

Workspace dependencies

---

CHANGELOG.md
pallets/ddc-payouts/src/lib.rs
pallets/ddc-payouts/src/mock.rs
pallets/ddc-payouts/src/tests.rs

more tests

---

runtime/cere/src/lib.rs

Use `from_parts` instead of `from_percent`

Hotfix: Testnet burn rate

---

runtime/cere/src/lib.rs

Hotfix: burn rate QANet

---

runtime/cere-dev/src/lib.rs
runtime/cere/src/lib.rs

Set the correct burn rate for Cere's runtime

---

runtime/cere/src/lib.rs

- Enable burn
- Re-introduce some migrations excluded in the previous release.

Hotfix: enable burn and migrations

---

Cargo.lock
Cargo.toml
node/service/Cargo.toml
node/service/src/lib.rs

fix: offchain workers are enabled

---

CHANGELOG.md
Cargo.lock
Cargo.toml

build: 5.1.0 release

---

.github/workflows/ci.yaml
CHANGELOG.md
Cargo.lock
Cargo.toml
node/service/Cargo.toml
node/service/src/lib.rs
pallets/ddc-customers/src/migration.rs
pallets/ddc-payouts/src/mock.rs
runtime/cere-dev/src/lib.rs
runtime/cere/src/lib.rs

Consolidating `master` and `dev` branches

---

.github/workflows/ci.yaml
CHANGELOG.md
Cargo.lock
Cargo.toml
node/service/Cargo.toml
node/service/src/lib.rs
pallets/ddc-customers/src/migration.rs
pallets/ddc-payouts/src/mock.rs
runtime/cere-dev/src/lib.rs
runtime/cere/src/lib.rs

Consolidating `staging` and `dev` branches

---

CHANGELOG.md
Cargo.lock
Cargo.toml
runtime/cere-dev/src/lib.rs
runtime/cere/src/lib.rs

5.1.2 RC-1

---

CHANGELOG.md
Cargo.lock
Cargo.toml
runtime/cere-dev/src/lib.rs
runtime/cere/src/lib.rs

Release 5.1.2

---

CHANGELOG.md
Cargo.lock
Cargo.toml
pallets/chainbridge/src/lib.rs
pallets/erc721/src/lib.rs
runtime/cere-dev/src/lib.rs
runtime/cere/src/lib.rs

Release 5.1.3

---

runtime/cere-dev/src/lib.rs
runtime/cere/src/lib.rs

Set Balances storage version

---

CHANGELOG.md
Cargo.lock
Cargo.toml
runtime/cere-dev/src/lib.rs
runtime/cere/src/lib.rs

- Inflation parameters for the staking reward curve are back to normal values
- Daily burning is set to 2.5%

Inflation parameters changed

---

CHANGELOG.md
Cargo.lock
Cargo.toml
runtime/cere-dev/src/lib.rs
runtime/cere/src/lib.rs

Merging PR #305 to 'dev' branch

---

Dockerfile.tests
runtime/cere-dev/src/lib.rs
runtime/cere/src/lib.rs

Fix build for release v5.2.0-rc1

---

runtime/cere-dev/src/lib.rs
runtime/cere/src/lib.rs

Remove migration to v8 since it's already executed

---

runtime/cere-dev/src/lib.rs
runtime/cere/src/lib.rs

Increment spec version

---

CHANGELOG.md
Cargo.lock
Cargo.toml
runtime/cere-dev/src/lib.rs
runtime/cere/src/lib.rs

Use original inflation params (#326)

---

CHANGELOG.md
Cargo.lock
Cargo.toml
pallets/ddc-customers/src/lib.rs
pallets/ddc-customers/src/tests.rs
runtime/cere-dev/src/lib.rs
runtime/cere/src/lib.rs

fix: depositing extra amount is fixed

---

CHANGELOG.md
Cargo.lock
Cargo.toml
pallets/ddc-customers/src/lib.rs
pallets/ddc-customers/src/tests.rs
runtime/cere-dev/src/lib.rs
runtime/cere/src/lib.rs

Companion for [Hotfix #333](https://github.com/Cerebellum-Network/blockchain-node/pull/333)

fix: depositing extra amount is fixed (#333)

---

pallets/ddc-clusters-gov/Cargo.toml
pallets/ddc-clusters-gov/src/mock.rs
pallets/ddc-clusters/src/lib.rs

Accept cluster replication props from genesis config

---

Cargo.lock
Cargo.toml
pallets/ddc-clusters/src/lib.rs
pallets/ddc-customers/src/mock.rs
pallets/ddc-nodes/src/lib.rs
pallets/ddc-payouts/src/lib.rs
pallets/ddc-staking/src/mock.rs
pallets/ddc-verification/Cargo.toml
pallets/ddc-verification/src/lib.rs
pallets/ddc-verification/src/mock.rs
pallets/ddc-verification/src/tests.rs
primitives/src/lib.rs
primitives/src/traits/cluster.rs
primitives/src/traits/node.rs
runtime/cere-dev/src/lib.rs
runtime/cere/src/lib.rs

Ddc construct etl

---

Cargo.lock
pallets/ddc-payouts/src/benchmarking.rs
pallets/ddc-payouts/src/lib.rs
pallets/ddc-payouts/src/mock.rs
pallets/ddc-payouts/src/tests.rs
pallets/ddc-payouts/src/weights.rs
pallets/ddc-verification/src/lib.rs
pallets/ddc-verification/src/mock.rs
pallets/ddc-verification/src/tests.rs
primitives/Cargo.toml
primitives/src/lib.rs
primitives/src/traits/validator.rs
runtime/cere-dev/src/lib.rs
runtime/cere/src/lib.rs

Fixes conflicts and changes for payout pallet validation

---

primitives/src/lib.rs

Fixed verification pallet tests

---

CHANGELOG.md
Cargo.lock
Cargo.toml
node/service/src/chain_spec.rs
runtime/cere-dev/src/governance/mod.rs
runtime/cere-dev/src/lib.rs
runtime/cere/src/governance/mod.rs
runtime/cere/src/lib.rs

This PR sets the WhitelistOrigin that has permission to approve pre-images (and therefore referendums) to the Technical Committee Collective body. This way, we will be able to upgrade the runtime via the `Whitelisted Caller` track without applying the SUDO call every time.

Technical committee as collective body is set for the WhitelistOrigin

---

CHANGELOG.md
node/service/src/chain_spec.rs
runtime/cere-dev/src/governance/mod.rs
runtime/cere-dev/src/lib.rs
runtime/cere/src/governance/mod.rs
runtime/cere/src/lib.rs

Backporting Tech Committee to the `dev` branch

---

runtime/cere/src/lib.rs

This PR sets the `StorageVersion` of the `TechComm` Pallet to [v4](https://github.com/paritytech/polkadot-sdk/blob/release-polkadot-v1.1.0/substrate/frame/collective/src/migrations/v4.rs) which was set by the latest migration available for the `CollectivePallet`. We don't need to execute the original migration as we are introducing a new instance of the `CollectivePallet` and don't do any renaming. This makes the `try-runtime` check happy.

FIX: Tech Comm storage version is set to v4

---

Cargo.lock
Cargo.toml
pallets/ddc-nodes/src/lib.rs
pallets/ddc-staking/src/mock.rs
pallets/ddc-verification/Cargo.toml
pallets/ddc-verification/src/lib.rs
pallets/ddc-verification/src/mock.rs
pallets/ddc-verification/src/tests.rs
primitives/src/lib.rs
primitives/src/traits/node.rs
runtime/cere-dev/src/lib.rs
runtime/cere/src/lib.rs

DCC Era validation

---

pallets/ddc-verification/src/benchmarking.rs
pallets/ddc-verification/src/lib.rs
pallets/ddc-verification/src/mock.rs
pallets/ddc-verification/src/tests.rs
primitives/src/lib.rs
runtime/cere-dev/src/lib.rs
runtime/cere/src/lib.rs

ddc processing + events

---

pallets/ddc-verification/src/lib.rs

Added documentation for Verification pallet

---

pallets/ddc-payouts/src/benchmarking.rs
pallets/ddc-payouts/src/lib.rs
pallets/ddc-payouts/src/mock.rs
pallets/ddc-payouts/src/tests.rs
pallets/ddc-verification/Cargo.toml
pallets/ddc-verification/src/lib.rs
pallets/ddc-verification/src/mock.rs
pallets/ddc-verification/src/tests.rs
primitives/src/lib.rs
primitives/src/traits/node.rs
primitives/src/traits/validator.rs
runtime/cere-dev/src/lib.rs
runtime/cere/src/lib.rs

payouts WIP

---

pallets/ddc-verification/src/lib.rs
pallets/ddc-verification/src/tests.rs

tests and fixes

---

Cargo.lock
Cargo.toml
pallets/ddc-payouts/Cargo.toml
pallets/ddc-payouts/src/benchmarking.rs
pallets/ddc-payouts/src/lib.rs
pallets/ddc-payouts/src/mock.rs
pallets/ddc-payouts/src/tests.rs
pallets/ddc-verification/Cargo.toml
pallets/ddc-verification/src/lib.rs
pallets/ddc-verification/src/tests.rs
primitives/Cargo.toml
primitives/src/lib.rs
primitives/src/traits/validator.rs

Merkle Proof implementation for Payout batch validation

---

CHANGELOG.md
runtime/cere-dev/src/governance/origins.rs
runtime/cere-dev/src/governance/tracks.rs
runtime/cere-dev/src/lib.rs
runtime/cere/src/governance/origins.rs
runtime/cere/src/governance/tracks.rs
runtime/cere/src/lib.rs

This PR introduces the following:
- Makes _Support Curve_ for OpenGov Tracks more strict to pass except the `Whitelisted Caller` Track that will be used for delivering hotfixes and new features
- Removes unused `FellowshipAdmin` origin and `fellowship_admin` track as we don't use it for updating members of our Technical Committee 
Below you can see the screenshots of Tracks with changed _Support Curves_:

Making Support Curve in OpenGov Tracks more strict

---

CHANGELOG.md
pallets/origins/src/lib.rs
runtime/cere-dev/src/governance/mod.rs
runtime/cere-dev/src/governance/tracks.rs
runtime/cere-dev/src/lib.rs
runtime/cere/src/governance/mod.rs
runtime/cere/src/governance/tracks.rs
runtime/cere/src/lib.rs
runtime/common/src/constants.rs

Backporting Referendum Support Curves to `dev` branch

---

pallets/ddc-verification/src/lib.rs

Corrected HTTP URLs

---

pallets/ddc-verification/src/lib.rs
pallets/ddc-verification/src/mock.rs
pallets/ddc-verification/src/tests.rs

Fixed HTTP Response Id issue

---

CHANGELOG.md
runtime/cere-dev/src/governance/origins.rs
runtime/cere-dev/src/governance/tracks.rs
runtime/cere-dev/src/lib.rs
runtime/cere/src/governance/origins.rs
runtime/cere/src/governance/tracks.rs
runtime/cere/src/lib.rs

Release 5.3.1 (with modified OpenGov Support Curves)

---

pallets/ddc-payouts/src/lib.rs
pallets/ddc-verification/src/lib.rs
pallets/ddc-verification/src/mock.rs
pallets/ddc-verification/src/tests.rs
primitives/src/lib.rs
primitives/src/traits/mod.rs
primitives/src/traits/payout.rs
runtime/cere-dev/src/lib.rs
runtime/cere/src/lib.rs

process_dac_data refactor + process_start_payout + tests

---

pallets/ddc-payouts/src/lib.rs
pallets/ddc-verification/src/lib.rs
pallets/ddc-verification/src/mock.rs
primitives/src/traits/payout.rs
runtime/cere-dev/src/lib.rs
runtime/cere/src/lib.rs

PayoutVisitor stash

---

.github/workflows/docker-image-berlin.yml
pallets/ddc-payouts/src/lib.rs
pallets/ddc-verification/src/lib.rs
pallets/ddc-verification/src/mock.rs
runtime/cere-dev/src/lib.rs
runtime/cere/src/lib.rs

Added Docker image for Berlin hackaton

---

pallets/ddc-nodes/src/lib.rs
pallets/ddc-staking/src/mock.rs
pallets/ddc-verification/src/lib.rs
pallets/ddc-verification/src/mock.rs
pallets/ddc-verification/src/tests.rs
primitives/src/traits/node.rs

Added method for setting cluster to validate

---

pallets/ddc-customers/src/lib.rs
pallets/ddc-customers/src/tests.rs
pallets/ddc-payouts/src/benchmarking.rs
pallets/ddc-payouts/src/lib.rs
pallets/ddc-payouts/src/mock.rs
pallets/ddc-payouts/src/tests.rs
pallets/ddc-verification/src/lib.rs
pallets/ddc-verification/src/mock.rs
primitives/src/traits/payout.rs
primitives/src/traits/validator.rs

ocw + payout step1

---

pallets/ddc-payouts/src/lib.rs
pallets/ddc-verification/src/lib.rs
pallets/ddc-verification/src/mock.rs
primitives/src/lib.rs
primitives/src/traits/payout.rs

begin billing -> end billing (without batches)

---

Cargo.lock
node/service/Cargo.toml
node/service/src/chain_spec.rs
pallets/ddc-verification/src/lib.rs
pallets/ddc-verification/src/tests.rs
runtime/cere-dev/src/lib.rs
runtime/cere/src/lib.rs
scripts/start_validator1.sh
scripts/start_validator2.sh
scripts/start_validator3.sh

Verification Pallet: Fix OCW issue

---

pallets/ddc-payouts/src/lib.rs
pallets/ddc-verification/src/lib.rs
pallets/ddc-verification/src/tests.rs

Fixed Start and End Era issue

---

pallets/ddc-verification/src/lib.rs
pallets/ddc-verification/src/tests.rs

empty activity for all nodes support

---

pallets/ddc-verification/src/lib.rs

Fix Era activity issue

---

Cargo.lock
pallets/ddc-payouts/Cargo.toml
pallets/ddc-payouts/src/benchmarking.rs
pallets/ddc-payouts/src/lib.rs
pallets/ddc-payouts/src/mock.rs
pallets/ddc-payouts/src/tests.rs
pallets/ddc-verification/src/lib.rs
pallets/ddc-verification/src/mock.rs
pallets/ddc-verification/src/tests.rs
primitives/src/lib.rs
primitives/src/traits/payout.rs
primitives/src/traits/validator.rs

Ocw payout charging customers

---

pallets/ddc-verification/src/lib.rs
pallets/ddc-verification/src/tests.rs
primitives/src/lib.rs

prepare_send_charging_customers_batch

---

pallets/ddc-customers/src/benchmarking.rs
pallets/ddc-customers/src/lib.rs
pallets/ddc-customers/src/migration.rs
pallets/ddc-customers/src/tests.rs
pallets/ddc-payouts/src/benchmarking.rs
pallets/ddc-payouts/src/lib.rs
pallets/ddc-payouts/src/mock.rs
pallets/ddc-payouts/src/tests.rs
pallets/ddc-verification/src/lib.rs
pallets/ddc-verification/src/mock.rs
primitives/src/lib.rs
primitives/src/traits/bucket.rs
primitives/src/traits/customer.rs
primitives/src/traits/payout.rs
primitives/src/traits/validator.rs
runtime/cere-dev/src/lib.rs
runtime/cere/src/lib.rs

Send rewarding providers batch

---

pallets/ddc-verification/src/lib.rs

disallow ocw signatures after era status change

---

pallets/ddc-customers/src/lib.rs
pallets/ddc-verification/src/lib.rs
pallets/ddc-verification/src/mock.rs
pallets/ddc-verification/src/tests.rs
runtime/cere-dev/src/lib.rs
runtime/cere/src/lib.rs

Fix for provider id

---

pallets/ddc-verification/src/lib.rs
runtime/cere-dev/src/lib.rs
runtime/cere/src/lib.rs

Commented out min node condition

---

pallets/ddc-verification/src/lib.rs
pallets/ddc-verification/src/mock.rs
pallets/ddc-verification/src/tests.rs
runtime/cere-dev/src/lib.rs
runtime/cere/src/lib.rs

Allow all nodes to participate

---

pallets/ddc-verification/src/lib.rs
runtime/cere-dev/src/lib.rs
runtime/cere/src/lib.rs

Fixed SSL condition

---

pallets/ddc-verification/src/lib.rs
runtime/cere-dev/src/lib.rs

Refactoring

---

pallets/ddc-payouts/src/lib.rs
pallets/ddc-verification/src/lib.rs
runtime/cere-dev/src/lib.rs

Add ocw information

---

pallets/ddc-customers/src/lib.rs
pallets/ddc-payouts/src/lib.rs
pallets/ddc-verification/src/lib.rs
primitives/src/lib.rs
runtime/cere-dev/src/lib.rs

Added debug information in payout

---

pallets/ddc-payouts/src/lib.rs
pallets/ddc-verification/src/lib.rs
runtime/cere-dev/src/lib.rs

Fixing Customer Id Ecoding Issue

---

Cargo.lock
Cargo.toml
pallets/ddc-verification/Cargo.toml
pallets/ddc-verification/src/lib.rs
runtime/cere-dev/src/lib.rs

Fixing customer id encoding

---

pallets/ddc-clusters/src/lib.rs
pallets/ddc-payouts/src/lib.rs
runtime/cere-dev/src/lib.rs

Fixing Cluster Migration

---

Cargo.lock
pallets/ddc-payouts/Cargo.toml
pallets/ddc-payouts/src/lib.rs
pallets/ddc-payouts/src/mock.rs
pallets/ddc-payouts/src/tests.rs
pallets/ddc-verification/src/lib.rs
pallets/ddc-verification/src/mock.rs
primitives/src/lib.rs
runtime/cere-dev/src/lib.rs
runtime/cere/src/lib.rs

Added Logs and Events for OCW-DAC Validation

---

Cargo.lock
pallets/ddc-nodes/Cargo.toml
pallets/ddc-nodes/src/lib.rs
pallets/ddc-nodes/src/migrations.rs
pallets/ddc-nodes/src/mock.rs
pallets/ddc-nodes/src/node.rs
pallets/ddc-nodes/src/storage_node.rs
pallets/ddc-nodes/src/tests.rs
pallets/ddc-payouts/src/lib.rs
pallets/ddc-payouts/src/mock.rs
pallets/ddc-payouts/src/tests.rs
pallets/ddc-verification/src/lib.rs
pallets/ddc-verification/src/mock.rs
pallets/ddc-verification/src/tests.rs
primitives/src/traits/node.rs
runtime/cere-dev/src/lib.rs
runtime/cere/src/lib.rs

node integer delta usage

---

pallets/ddc-verification/src/lib.rs
runtime/cere-dev/src/lib.rs
runtime/cere/src/lib.rs

Added OCW activity logs

---

pallets/ddc-verification/src/lib.rs
pallets/ddc-verification/src/tests.rs
runtime/cere-dev/src/lib.rs
runtime/cere/src/lib.rs

Added logs for activity

---

.github/workflows/ci.yaml
runtime/cere-dev/src/governance/tracks.rs
runtime/cere-dev/src/lib.rs
runtime/cere/src/governance/tracks.rs
runtime/cere/src/lib.rs
runtime/common/src/constants.rs

On-chain parameters for `ClusterGov`

---

.github/workflows/ci.yaml
runtime/cere-dev/src/lib.rs

Added try-runtime check in CI

---

pallets/ddc-verification/src/lib.rs
runtime/cere-dev/src/lib.rs
runtime/cere/src/lib.rs

Check for not-processed eras

---

.github/workflows/ci.yaml
runtime/cere-dev/src/governance/tracks.rs
runtime/cere-dev/src/lib.rs
runtime/cere/src/governance/tracks.rs
runtime/cere/src/lib.rs
runtime/common/src/constants.rs

ClusterGov params on-chain params

---

pallets/ddc-verification/src/lib.rs
runtime/cere-dev/src/lib.rs
runtime/cere/src/lib.rs

Changes to fix unprocessed eras

---

.github/workflows/stage.yaml
CHANGELOG.md
Cargo.lock
Cargo.toml
node/client/src/lib.rs
node/service/src/lib.rs
pallets/ddc-clusters-gov/src/mock.rs
pallets/ddc-payouts/src/mock.rs
pallets/ddc-payouts/src/tests.rs
runtime/cere-dev/src/governance/tracks.rs
runtime/cere-dev/src/lib.rs
runtime/cere/src/governance/tracks.rs
runtime/cere/src/lib.rs
runtime/common/src/constants.rs

This PR backports `polkadot-sdk 1.2` from the `new-staging` branch, and production settings for the `ClusterGov`

Devnet: polkadot-sdk 1.2 and missing commits from the `new-staging` branch

---

Cargo.lock
Cargo.toml
runtime/cere-dev/src/lib.rs
runtime/cere/src/lib.rs

This PR aligns the runtime version of Devnet with Qanet

build: Devnet runtime version is aligned with Qanet

---

pallets/ddc-verification/src/lib.rs
pallets/ddc-verification/src/tests.rs
runtime/cere-dev/src/lib.rs

This PR prevents double spending in case of inconsistent aggregates for the same aggregation key that may occur due to bugs on Aggregators side

FIX: Preventing double spending in case of inconsistent aggregates for the same aggregation key

---

Cargo.lock
pallets/ddc-clusters/src/lib.rs
pallets/ddc-customers/src/mock.rs
pallets/ddc-verification/src/lib.rs
pallets/ddc-verification/src/migrations.rs
pallets/ddc-verification/src/mock.rs
pallets/ddc-verification/src/tests.rs
primitives/Cargo.toml
primitives/src/lib.rs
primitives/src/traits/cluster.rs
runtime/cere-dev/src/lib.rs
runtime/cere/src/lib.rs

This PR enables DAC validation for all DDC Clusters in the `Activated` status, which can be obtained only after passing the public referendum.
It also disables the strict requirement on the number of expected responses from DAC nodes and lets the OCW Validation cycles proceed if some Aggregators for the validating era are inaccessible due to networking issues or downtime.
Lastly, it fixes the problem for newly-joined validators and allows them to start validating process for eras newer than the last validated era for a cluster.

Supporting multiple clusters for DAC validation

---

pallets/ddc-verification/Cargo.toml

It enables runtime-benchmarks feature for `ddc-primitives` in `pallet-ddc-verification` feature enabled build. 

Fix runtime-benchmarks build for ddc-verification

---

pallets/ddc-verification/src/aggregator_client.rs
pallets/ddc-verification/src/lib.rs
pallets/ddc-verification/src/tests.rs

A little step to simplify `pallet-ddc-verification` maintenance.

Offload aggregator's API JSON definitions from ddc-verification pallet mod

---

pallets/ddc-verification/src/lib.rs
runtime/cere-dev/src/lib.rs
runtime/cere/src/lib.rs

This PR refactors the verification OCW source code by the following:
- It introduces individual steps and functions for validation and payouts phases
- It removes iterators over results from multiple submissions by calling the `send_single_signed_transaction` method instead of `send_signed_transaction` method on the Signer
- It introduces a macro for payout repetitive steps
- It standardizes the `info!` and `error!` log outputs in validation and payouts phases

Allocating validation and payouts phases to individual functions. Introducing macro for payouts repetitive steps

---

Cargo.lock
pallets/ddc-verification/Cargo.toml
pallets/ddc-verification/src/aggregator_client.rs
pallets/ddc-verification/src/lib.rs
pallets/ddc-verification/src/mock.rs
pallets/ddc-verification/src/signature.rs
pallets/ddc-verification/src/test_data/activity_buckets_signed_resp.json
pallets/ddc-verification/src/tests.rs
runtime/cere-dev/src/lib.rs
runtime/cere/src/lib.rs

Ask aggregator to sign JSON response signature and verify it before processing.

Verify aggregator's response signature

---

pallets/ddc-verification/src/aggregator_client.rs
runtime/cere-dev/src/lib.rs
runtime/cere/src/lib.rs

Fix `/activity/eras` optional parameter.

Fix `/activity/eras` optional param

---

.github/workflows/ci.yaml
node/cli/Cargo.toml
node/cli/src/command.rs
node/service/src/chain_spec.rs
runtime/cere-dev/src/lib.rs
runtime/cere/src/lib.rs

This PR introduces a template for the `cere` runtime to launch thirdparty networks.

Mainnet template for running thirdparty networks

---

.github/workflows/ci.yaml
pallets/ddc-verification/src/aggregator_client.rs
pallets/ddc-verification/src/lib.rs
pallets/ddc-verification/src/mock.rs
runtime/cere-dev/src/lib.rs
runtime/cere/src/lib.rs

This PR allows Inspector OCW to skip payouts for empty eras

Skipping payouts for eras without activity

---

pallets/ddc-verification/src/aggregator_client.rs
pallets/ddc-verification/src/lib.rs
pallets/ddc-verification/src/tests.rs
runtime/cere-dev/src/lib.rs
runtime/cere/src/lib.rs

Fetching G-Collectors dynamically

---

pallets/ddc-verification/src/aggregator_client.rs
pallets/ddc-verification/src/lib.rs
pallets/ddc-verification/src/mock.rs
runtime/cere-dev/src/lib.rs
runtime/cere/src/lib.rs

Cutting of unverified activity from Payouts

---

pallets/ddc-clusters/src/cluster.rs
pallets/ddc-clusters/src/lib.rs
pallets/ddc-clusters/src/migrations.rs
pallets/ddc-clusters/src/tests.rs
pallets/ddc-payouts/src/lib.rs
pallets/ddc-payouts/src/migrations.rs
pallets/ddc-payouts/src/mock.rs
pallets/ddc-staking/src/tests.rs
pallets/ddc-verification/src/aggregator_client.rs
pallets/ddc-verification/src/benchmarking.rs
pallets/ddc-verification/src/insp_ddc_api.rs
pallets/ddc-verification/src/insp_task_manager.rs
pallets/ddc-verification/src/lib.rs
pallets/ddc-verification/src/mock.rs
pallets/ddc-verification/src/tests.rs
primitives/src/lib.rs
primitives/src/traits/cluster.rs
runtime/cere-dev/src/lib.rs
runtime/cere/src/lib.rs

This PR introduces the inspection assignments table that contains inspection paths assigned to a set of primary and backup Inspectors 

Inspection assignments table and Inspection paths distribution

---

pallets/ddc-payouts/src/lib.rs
pallets/ddc-payouts/src/migrations.rs
pallets/ddc-payouts/src/tests.rs
pallets/ddc-verification/src/benchmarking.rs
pallets/ddc-verification/src/insp_task_manager.rs
pallets/ddc-verification/src/lib.rs
pallets/ddc-verification/src/mock.rs
primitives/src/traits/payout.rs
runtime/cere-dev/src/lib.rs
runtime/cere/src/lib.rs

We need to be able to quickly retrieve a hash of the block where the payout was finalized. It is needed for determinism while assigning roles in DDC such as G-Collector, Collector, Sync Node, etc. As the hash of the block is not available while executing the payout finalization transaction, we store the block number as a reference.  

Indexing block number when payout phase is finalized

---

runtime/cere-dev/src/lib.rs
runtime/cere/src/hyperbridge_ismp.rs
runtime/cere/src/lib.rs

Update Hyperbridge config for testnet

---

CHANGELOG.md
Cargo.lock
Cargo.toml
pallets/fee-handler/src/lib.rs
runtime/cere-dev/src/lib.rs
runtime/cere/src/lib.rs

Added extrinsic to burn Tokens

---

Cargo.lock
runtime/cere-dev/src/lib.rs
runtime/cere/src/lib.rs

FIX: ignoring TCAs for inconsistent aggregates between collectors

---

runtime/cere-dev/src/lib.rs
runtime/cere/src/hyperbridge_ismp.rs
runtime/cere/src/lib.rs

Update Hyperbridge Config on Mainnet

---

Cargo.lock
runtime/cere-dev/src/lib.rs
runtime/cere/src/lib.rs

Ignoring removed content during payouts

---

Cargo.lock
Cargo.toml
node/service/src/chain_spec.rs
pallets/ddc-clusters/src/lib.rs
pallets/ddc-clusters/src/testing_utils.rs
pallets/ddc-clusters/src/tests.rs
pallets/ddc-customers/src/lib.rs
pallets/ddc-customers/src/mock.rs
runtime/cere-dev/src/lib.rs
runtime/cere/src/lib.rs

FIX: Integration Tests and benchmarks

---

pallets/ddc-clusters/src/lib.rs
pallets/ddc-clusters/src/testing_utils.rs
pallets/ddc-clusters/src/tests.rs
pallets/ddc-customers/src/lib.rs
pallets/ddc-customers/src/mock.rs
runtime/cere-dev/src/lib.rs
runtime/cere/src/lib.rs

Fixed the mocks and tests for benchmarks to work

Fixed the mocks and tests for benchmarks to work

---

.github/workflows/generate_weights.yml
.gitignore
.vscode/settings.json

weights generation init

---

.github/workflows/ci.yaml
Cargo.lock
Cargo.toml
pallets/ddc-customers/src/lib.rs
pallets/ddc-customers/src/migrations.rs
runtime/cere-dev/src/lib.rs
runtime/cere/src/lib.rs

Migration fix for transferring the actual balance from pallet vault to cluster vault

---

Cargo.lock
runtime/cere-dev/src/lib.rs
runtime/cere/src/lib.rs

Testnet in `staging`

---

Cargo.lock
runtime/cere-dev/src/lib.rs
runtime/cere/src/lib.rs

FIX: fetching missing ARs from collector that was assigned in inspection table

---

Cargo.lock
Cargo.toml
runtime/cere-dev/src/lib.rs
runtime/cere/src/lib.rs

build: dependencies upgrade

---

Cargo.lock
Cargo.toml

Release/73151 (fee-less operational transactions)

---

Cargo.lock
runtime/cere-dev/src/lib.rs
runtime/cere/src/lib.rs

Defining IRF number dynamically depending on available validators number; Fix for unsigned tx tag uniqueness

---

Cargo.lock
runtime/cere-dev/src/lib.rs
runtime/cere/src/lib.rs

DEVNET dependencies upgrade

---

Cargo.lock
runtime/cere-dev/src/lib.rs
runtime/cere/src/lib.rs

fix: api response for inspection state is fixed at DDC side

---

Cargo.lock
runtime/cere-dev/src/lib.rs
runtime/cere/src/lib.rs

Added dust balance handler

---

runtime/cere-dev/src/lib.rs
runtime/cere/src/lib.rs

Increased spec version

---

.github/workflows/ci.yaml
.rustfmt.toml
docs/SECURITY_EXECUTION_PLAN.md
github-checks.sh
node/cli/src/command.rs
node/service/src/lib.rs
pallets/ddc-clusters-gov/src/benchmarking.rs
pallets/ddc-clusters-gov/src/mock_clusters_gov.rs
pallets/ddc-clusters/src/lib.rs
pallets/ddc-clusters/src/testing_utils.rs
pallets/ddc-customers/src/lib.rs
pallets/ddc-customers/src/migrations.rs
pallets/ddc-nodes/src/lib.rs
pallets/ddc-nodes/src/migrations.rs
pallets/ddc-nodes/src/node.rs
pallets/ddc-staking/src/lib.rs
pallets/ddc-staking/src/migrations.rs
runtime/cere-dev/src/governance/mod.rs
runtime/cere-dev/src/governance/tracks.rs
runtime/cere-dev/src/hyperbridge_ismp.rs
runtime/cere-dev/src/lib.rs
runtime/cere/src/governance/mod.rs
runtime/cere/src/governance/tracks.rs
runtime/cere/src/hyperbridge_ismp.rs
runtime/cere/src/lib.rs
scripts/pre-commit.sh

Fix toolchain: nightly to stable Rust 1.82.0

---

.github/workflows/stage.yaml
Dockerfile

Fix Release to Stage Pipeline

---

CHANGELOG.md
Cargo.toml
runtime/cere-dev/src/lib.rs
runtime/cere/src/lib.rs

Redirect Dust Balances to Treasury Instead of Burning to Fix total Issuance issue

---

CHANGELOG.md
Cargo.lock
Cargo.toml
runtime/cere-dev/Cargo.toml
runtime/cere-dev/src/lib.rs
runtime/cere/Cargo.toml
runtime/cere/src/lib.rs

Fixed low Transaction fee issue and removed depreicated depndencies.

Fixed low Transaction fee issue, removed depreicated depndencies and implemented

---

.github/workflows/ci.yaml
docker-compose.monitoring.yml
docs/PHASE4_MONITORING_COMPLIANCE.md
monitoring/alertmanager.yml
monitoring/grafana/dashboards/compliance-dashboard.json
monitoring/grafana/dashboards/security-dashboard.json
monitoring/grafana/datasources/prometheus.yml
monitoring/prometheus.yml
monitoring/rules/security-alerts.yml
node/service/src/chain_spec.rs
node/service/src/network_security.rs

I have successfully implemented a comprehensive monitoring and compliance framework for the Cere blockchain node as specified in Phase 4 of the security execution plan. Here's what was accomplished:
Monitoring Infrastructure:
- Created `docker-compose.monitoring.yml` - Complete monitoring stack with Prometheus, Grafana, AlertManager, Loki, Jaeger, and Node Exporter
- Created `monitoring/prometheus.yml` - Prometheus configuration with scrape targets and alerting rules
- Created `monitoring/rules/security-alerts.yml` - Comprehensive security alerting rules
- Created `monitoring/alertmanager.yml` - Alert routing and notification configuration
Grafana Dashboards:
- Created `monitoring/grafana/dashboards/security-dashboard.json` - Real-time security metrics visualization
- Created …

Phase4 monitoring compliance new

---

.github/workflows/security.yaml
.github/workflows/stage.yaml

Comprehensive Disk Space Management Added :
- Aggressive cleanup : Removes .NET, Android SDK, PowerShell, Swift, Azure CLI, Node modules, and hosted toolcache
- Package management : Purges unnecessary packages and cleans apt caches
- Docker optimization : Prunes Docker system and builder cache before and after builds
- Proactive monitoring : Tracks disk usage at multiple workflow stages
- Early detection : Fails fast if available space drops below 10GB
- Post-build cleanup : Automatically prunes dangling Docker images

Fix security workflow: Add comprehensive disk space management

---

Cargo.lock
runtime/cere-dev/src/lib.rs
runtime/cere/src/lib.rs

FIX: Total charged amount calculation in DDC payouts

---

.github/workflows/stage.yaml
CHANGELOG.md
Cargo.lock
Cargo.toml
pallets/pool-withdrawal-fix/Cargo.toml
pallets/pool-withdrawal-fix/src/lib.rs
runtime/cere-dev/Cargo.toml
runtime/cere-dev/src/lib.rs
runtime/cere/Cargo.toml
runtime/cere/src/lib.rs

Added pool-withdrawal-fix [QANET]
